# Generated by Django 3.1.5 on 2021-09-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20210903_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='summary',
            field=models.TextField(blank=True, default='ok this is default'),
            preserve_default=False,
        ),
    ]
